
[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@sendgrid/mail", "node-fetch", "zod"]

# Map /api/* to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback for React Router (wouter)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
